import { NatureSide, Statement } from "./types";

/**
 * Schedule of heads per the ICAI "Guidance Note on Financial Statements of
 * Non-Corporate Entities" (Revised 2024) - Division I (entities to which
 * Ind AS is not applicable). Adapted for Proprietorship / Partnership / LLP.
 */
export interface ScheduleGroup {
  key: string;
  label: string;
  statement: Statement;
  side: NatureSide;
  section: string;
  order: number;
  hasNote: boolean;
  /** Only rendered on face of statement for these entity types; undefined = all */
  entityTypes?: Array<"proprietorship" | "partnership" | "llp">;
  keywords: RegExp[];
}

export const SECTIONS = {
  OWNERS_FUND: "Owners' Fund",
  NON_CURRENT_LIAB: "Non-current liabilities",
  CURRENT_LIAB: "Current liabilities",
  NON_CURRENT_ASSETS: "Non-current assets",
  CURRENT_ASSETS: "Current assets",
  INCOME: "Income",
  EXPENSES: "Expenses",
  PROFIT_APPROPRIATION: "Profit Appropriation",
  TAX: "Tax Expense",
};

export const SCHEDULE_GROUPS: ScheduleGroup[] = [
  // ---------------- Balance Sheet: Equity & Liabilities ----------------
  {
    key: "owners_capital",
    label: "Proprietor's / Partners' Capital Accounts",
    statement: "BS",
    side: "EquityLiability",
    section: SECTIONS.OWNERS_FUND,
    order: 10,
    hasNote: true,
    keywords: [/capital account/i, /proprietor.*capital/i, /partner.*capital/i, /^capital$/i],
  },
  {
    key: "reserves_surplus",
    label: "Reserves and Surplus",
    statement: "BS",
    side: "EquityLiability",
    section: SECTIONS.OWNERS_FUND,
    order: 20,
    hasNote: true,
    keywords: [/reserve/i, /surplus/i, /general reserve/i, /profit\s*(&|and)?\s*loss\s*(a\/?c|account)?$/i, /accumulated profit/i],
  },
  {
    key: "lt_borrowings",
    label: "Long-term borrowings",
    statement: "BS",
    side: "EquityLiability",
    section: SECTIONS.NON_CURRENT_LIAB,
    order: 30,
    hasNote: true,
    keywords: [/term loan/i, /debenture/i, /vehicle loan/i, /housing loan/i, /long.?term loan/i],
  },
  {
    key: "deferred_tax_liab",
    label: "Deferred tax liabilities (net)",
    statement: "BS",
    side: "EquityLiability",
    section: SECTIONS.NON_CURRENT_LIAB,
    order: 40,
    hasNote: true,
    keywords: [/deferred tax liab/i],
  },
  {
    key: "other_lt_liabilities",
    label: "Other long-term liabilities",
    statement: "BS",
    side: "EquityLiability",
    section: SECTIONS.NON_CURRENT_LIAB,
    order: 50,
    hasNote: true,
    keywords: [/security deposit received/i, /retention money.*long/i],
  },
  {
    key: "lt_provisions",
    label: "Long-term provisions",
    statement: "BS",
    side: "EquityLiability",
    section: SECTIONS.NON_CURRENT_LIAB,
    order: 60,
    hasNote: true,
    keywords: [/provision for gratuity/i, /provision for leave encashment/i, /provision.*long.?term/i],
  },
  {
    key: "st_borrowings",
    label: "Short-term borrowings",
    statement: "BS",
    side: "EquityLiability",
    section: SECTIONS.CURRENT_LIAB,
    order: 70,
    hasNote: true,
    keywords: [/cash credit/i, /overdraft/i, /bank od/i, /working capital loan/i, /short.?term loan/i],
  },
  {
    key: "trade_payables_msme",
    label: "total outstanding dues of micro enterprises and small enterprises",
    statement: "BS",
    side: "EquityLiability",
    section: SECTIONS.CURRENT_LIAB,
    order: 80,
    hasNote: true,
    keywords: [],
  },
  {
    key: "trade_payables_others",
    label: "total outstanding dues of creditors other than micro enterprises and small enterprises",
    statement: "BS",
    side: "EquityLiability",
    section: SECTIONS.CURRENT_LIAB,
    order: 90,
    hasNote: true,
    keywords: [/sundry creditors/i, /trade payable/i, /creditors for/i, /^creditors/i, /payable/i],
  },
  {
    key: "other_current_liabilities",
    label: "Other current liabilities",
    statement: "BS",
    side: "EquityLiability",
    section: SECTIONS.CURRENT_LIAB,
    order: 100,
    hasNote: true,
    keywords: [/outstanding expense/i, /duties.*taxes/i, /tds payable/i, /gst payable/i, /statutory dues/i, /advance from customer/i, /unpaid/i, /tcs payable/i, /pf payable/i, /esi payable/i],
  },
  {
    key: "st_provisions",
    label: "Short-term provisions",
    statement: "BS",
    side: "EquityLiability",
    section: SECTIONS.CURRENT_LIAB,
    order: 110,
    hasNote: true,
    keywords: [/provision for tax/i, /provision for expense/i, /provision for bonus/i, /provision for audit/i],
  },

  // ---------------- Balance Sheet: Assets ----------------
  {
    key: "ppe",
    label: "Property, Plant and Equipment",
    statement: "BS",
    side: "Asset",
    section: SECTIONS.NON_CURRENT_ASSETS,
    order: 120,
    hasNote: true,
    keywords: [/land/i, /building/i, /plant.*machinery/i, /furniture/i, /fixture/i, /vehicle/i, /computer/i, /office equipment/i, /fixed asset/i, /electrical installation/i],
  },
  {
    key: "cwip",
    label: "Capital work-in-progress",
    statement: "BS",
    side: "Asset",
    section: SECTIONS.NON_CURRENT_ASSETS,
    order: 130,
    hasNote: true,
    keywords: [/capital work.?in.?progress/i, /\bcwip\b/i],
  },
  {
    key: "investment_property",
    label: "Investment Property",
    statement: "BS",
    side: "Asset",
    section: SECTIONS.NON_CURRENT_ASSETS,
    order: 140,
    hasNote: true,
    keywords: [/investment property/i],
  },
  {
    key: "goodwill",
    label: "Goodwill",
    statement: "BS",
    side: "Asset",
    section: SECTIONS.NON_CURRENT_ASSETS,
    order: 150,
    hasNote: true,
    keywords: [/goodwill/i],
  },
  {
    key: "intangible_assets",
    label: "Other Intangible assets",
    statement: "BS",
    side: "Asset",
    section: SECTIONS.NON_CURRENT_ASSETS,
    order: 160,
    hasNote: true,
    keywords: [/software/i, /patent/i, /trademark/i, /intangible/i, /copyright/i],
  },
  {
    key: "nc_investments",
    label: "Non-current investments",
    statement: "BS",
    side: "Asset",
    section: SECTIONS.NON_CURRENT_ASSETS,
    order: 170,
    hasNote: true,
    keywords: [/investment in shares/i, /investment in subsidiary/i, /investment.*long.?term/i],
  },
  {
    key: "deferred_tax_asset",
    label: "Deferred tax assets (net)",
    statement: "BS",
    side: "Asset",
    section: SECTIONS.NON_CURRENT_ASSETS,
    order: 180,
    hasNote: true,
    keywords: [/deferred tax asset/i],
  },
  {
    key: "lt_loans_advances",
    label: "Long-term loans and advances",
    statement: "BS",
    side: "Asset",
    section: SECTIONS.NON_CURRENT_ASSETS,
    order: 190,
    hasNote: true,
    keywords: [/security deposit paid/i, /security deposit given/i, /capital advance/i],
  },
  {
    key: "other_nc_assets",
    label: "Other non-current assets",
    statement: "BS",
    side: "Asset",
    section: SECTIONS.NON_CURRENT_ASSETS,
    order: 200,
    hasNote: true,
    keywords: [],
  },
  {
    key: "current_investments",
    label: "Current investments",
    statement: "BS",
    side: "Asset",
    section: SECTIONS.CURRENT_ASSETS,
    order: 210,
    hasNote: true,
    keywords: [/mutual fund/i, /investment.*current/i],
  },
  {
    key: "inventories",
    label: "Inventories",
    statement: "BS",
    side: "Asset",
    section: SECTIONS.CURRENT_ASSETS,
    order: 220,
    hasNote: true,
    keywords: [/closing stock/i, /^stock/i, /inventory/i, /raw material/i, /finished goods/i, /stock.in.trade/i, /work.?in.?progress/i],
  },
  {
    key: "trade_receivables",
    label: "Trade receivables",
    statement: "BS",
    side: "Asset",
    section: SECTIONS.CURRENT_ASSETS,
    order: 230,
    hasNote: true,
    keywords: [/sundry debtor/i, /trade receivable/i, /^debtors/i, /accounts receivable/i],
  },
  {
    key: "cash_and_bank",
    label: "Cash and cash equivalents",
    statement: "BS",
    side: "Asset",
    section: SECTIONS.CURRENT_ASSETS,
    order: 240,
    hasNote: true,
    keywords: [/cash in hand/i, /cash at bank/i, /bank account/i, /petty cash/i, /^cash$/i, /fixed deposit/i, /\bfdr\b/i],
  },
  {
    key: "st_loans_advances",
    label: "Short-term loans and advances",
    statement: "BS",
    side: "Asset",
    section: SECTIONS.CURRENT_ASSETS,
    order: 250,
    hasNote: true,
    keywords: [/advance to supplier/i, /advance to staff/i, /prepaid expense/i, /loans and advances/i, /tds receivable/i, /advance tax/i, /gst input/i, /input tax credit/i, /\bitc\b/i],
  },
  {
    key: "other_current_assets",
    label: "Other current assets",
    statement: "BS",
    side: "Asset",
    section: SECTIONS.CURRENT_ASSETS,
    order: 260,
    hasNote: true,
    keywords: [/accrued income/i, /interest receivable/i],
  },

  // ---------------- Profit & Loss: Income ----------------
  {
    key: "revenue_from_operations",
    label: "Revenue from operations",
    statement: "PL",
    side: "Income",
    section: SECTIONS.INCOME,
    order: 300,
    hasNote: true,
    keywords: [/^sales/i, /revenue from operations/i, /service income/i, /gross receipts/i, /turnover/i, /sale of/i],
  },
  {
    key: "other_income",
    label: "Other income",
    statement: "PL",
    side: "Income",
    section: SECTIONS.INCOME,
    order: 310,
    hasNote: true,
    keywords: [/interest income/i, /interest received/i, /dividend income/i, /discount received/i, /rent received/i, /misc income/i, /miscellaneous income/i, /profit on sale/i],
  },

  // ---------------- Profit & Loss: Expenses ----------------
  {
    key: "cost_of_materials",
    label: "Cost of materials consumed",
    statement: "PL",
    side: "Expense",
    section: SECTIONS.EXPENSES,
    order: 320,
    hasNote: true,
    keywords: [/material consumed/i, /cost of material/i, /raw material purchase/i],
  },
  {
    key: "purchases_stock_in_trade",
    label: "Purchases of Stock-in-Trade",
    statement: "PL",
    side: "Expense",
    section: SECTIONS.EXPENSES,
    order: 330,
    hasNote: true,
    keywords: [/^purchases?$/i, /purchase of goods/i, /purchase account/i],
  },
  {
    key: "changes_in_inventories",
    label: "Changes in inventories of finished goods, work-in-progress and stock-in-trade",
    statement: "PL",
    side: "Expense",
    section: SECTIONS.EXPENSES,
    order: 340,
    hasNote: true,
    keywords: [/increase.*decrease.*stock/i, /change.*inventor/i, /stock adjustment/i],
  },
  {
    key: "employee_benefits",
    label: "Employee benefits expense",
    statement: "PL",
    side: "Expense",
    section: SECTIONS.EXPENSES,
    order: 350,
    hasNote: true,
    keywords: [/salary/i, /wages/i, /staff welfare/i, /\bbonus\b/i, /gratuity expense/i, /\bpf\b/i, /provident fund/i, /\besi\b/i, /employee benefit/i, /staff cost/i],
  },
  {
    key: "finance_costs",
    label: "Finance costs",
    statement: "PL",
    side: "Expense",
    section: SECTIONS.EXPENSES,
    order: 360,
    hasNote: true,
    keywords: [/interest paid/i, /interest on loan/i, /interest expense/i, /bank charges/i, /loan processing fee/i, /finance cost/i, /interest on od/i, /interest on cc/i],
  },
  {
    key: "depreciation_amortization",
    label: "Depreciation and amortization expense",
    statement: "PL",
    side: "Expense",
    section: SECTIONS.EXPENSES,
    order: 370,
    hasNote: true,
    keywords: [/depreciation/i, /amorti[sz]ation/i],
  },
  {
    key: "other_expenses",
    label: "Other expenses",
    statement: "PL",
    side: "Expense",
    section: SECTIONS.EXPENSES,
    order: 380,
    hasNote: true,
    keywords: [/rent/i, /rates.*taxes/i, /electricity/i, /power.*fuel/i, /repairs/i, /printing.*stationery/i, /travelling/i, /conveyance/i, /telephone/i, /internet/i, /legal.*professional/i, /audit fee/i, /insurance/i, /advertisement/i, /commission/i, /freight/i, /postage/i, /general expense/i, /misc(ellaneous)? expense/i, /donation/i, /membership/i, /round.?off/i],
  },
  {
    key: "partners_remuneration",
    label: "Remuneration and Interest to Partners",
    statement: "PL",
    side: "Expense",
    section: SECTIONS.PROFIT_APPROPRIATION,
    order: 390,
    hasNote: true,
    entityTypes: ["partnership"],
    keywords: [/partner.*remuneration/i, /partner.*salary/i, /interest on capital/i, /partner.*interest/i],
  },
  {
    key: "current_tax",
    label: "Current tax",
    statement: "PL",
    side: "Expense",
    section: SECTIONS.TAX,
    order: 400,
    hasNote: true,
    entityTypes: ["partnership", "llp"],
    keywords: [/provision for income tax/i, /^income tax$/i, /current tax/i],
  },
  {
    key: "deferred_tax_pl",
    label: "Deferred tax",
    statement: "PL",
    side: "Expense",
    section: SECTIONS.TAX,
    order: 410,
    hasNote: true,
    entityTypes: ["partnership", "llp"],
    keywords: [/deferred tax/i],
  },
];

export function getGroup(key: string | null | undefined): ScheduleGroup | undefined {
  if (!key) return undefined;
  return SCHEDULE_GROUPS.find((g) => g.key === key);
}

export function groupsForEntity(entityType: "proprietorship" | "partnership" | "llp") {
  return SCHEDULE_GROUPS.filter((g) => !g.entityTypes || g.entityTypes.includes(entityType));
}

export const ROUNDING_FACTORS: Record<string, number> = {
  actual: 1,
  hundreds: 100,
  thousands: 1000,
  lakhs: 100000,
  crores: 10000000,
  millions: 1000000,
};

export const ENTITY_TYPE_LABELS: Record<string, string> = {
  proprietorship: "Sole Proprietorship",
  partnership: "Partnership Firm",
  llp: "Limited Liability Partnership (LLP)",
};
