# Mirrors src/lib/schema.ts SCHEDULE_GROUPS - ICAI Guidance Note Division I
# (key, label, statement, side, section, order, entity_types_or_None, keywords[])
GROUPS = [
    ("owners_capital", "Proprietor's / Partners' Capital Accounts", "BS", "EquityLiability", "Owners' Fund", 10, None,
     ["capital account", "proprietor", "partner", "capital"]),
    ("reserves_surplus", "Reserves and Surplus", "BS", "EquityLiability", "Owners' Fund", 20, None,
     ["reserve", "surplus", "accumulated profit"]),
    ("lt_borrowings", "Long-term borrowings", "BS", "EquityLiability", "Non-current liabilities", 30, None,
     ["term loan", "debenture", "vehicle loan", "housing loan", "secured loan", "unsecured loan", "loans (liability)"]),
    ("deferred_tax_liab", "Deferred tax liabilities (net)", "BS", "EquityLiability", "Non-current liabilities", 40, None,
     ["deferred tax liab"]),
    ("other_lt_liabilities", "Other long-term liabilities", "BS", "EquityLiability", "Non-current liabilities", 50, None,
     ["security deposit received", "retention money"]),
    ("lt_provisions", "Long-term provisions", "BS", "EquityLiability", "Non-current liabilities", 60, None,
     ["provision for gratuity", "provision for leave"]),
    ("st_borrowings", "Short-term borrowings", "BS", "EquityLiability", "Current liabilities", 70, None,
     ["cash credit", "overdraft", "bank od", "working capital loan", "short term loan", "short-term loan"]),
    ("trade_payables_msme", "total outstanding dues of micro enterprises and small enterprises", "BS", "EquityLiability", "Current liabilities", 80, None,
     []),
    ("trade_payables_others", "total outstanding dues of creditors other than micro enterprises and small enterprises", "BS", "EquityLiability", "Current liabilities", 90, None,
     ["sundry creditor", "trade payable", "creditors for", "creditors", "payable"]),
    ("other_current_liabilities", "Other current liabilities", "BS", "EquityLiability", "Current liabilities", 100, None,
     ["outstanding expense", "duties", "tax payable", "tds payable", "gst payable", "statutory dues", "advance from customer", "unpaid", "tcs payable", "pf payable", "esi payable"]),
    ("st_provisions", "Short-term provisions", "BS", "EquityLiability", "Current liabilities", 110, None,
     ["provision for tax", "provision for expense", "provision for bonus", "provision for audit"]),
    ("ppe", "Property, Plant and Equipment", "BS", "Asset", "Non-current assets", 120, None,
     ["land", "building", "plant", "machinery", "furniture", "fixture", "vehicle", "computer", "office equipment", "fixed asset", "electrical installation", "printer", "car"]),
    ("cwip", "Capital work-in-progress", "BS", "Asset", "Non-current assets", 130, None,
     ["capital work", "cwip"]),
    ("investment_property", "Investment Property", "BS", "Asset", "Non-current assets", 140, None,
     ["investment property"]),
    ("goodwill", "Goodwill", "BS", "Asset", "Non-current assets", 150, None,
     ["goodwill"]),
    ("intangible_assets", "Other Intangible assets", "BS", "Asset", "Non-current assets", 160, None,
     ["software", "patent", "trademark", "intangible", "copyright"]),
    ("nc_investments", "Non-current investments", "BS", "Asset", "Non-current assets", 170, None,
     ["investment in shares", "investment in subsidiary", "long term investment", "long-term investment"]),
    ("deferred_tax_asset", "Deferred tax assets (net)", "BS", "Asset", "Non-current assets", 180, None,
     ["deferred tax asset"]),
    ("lt_loans_advances", "Long-term loans and advances", "BS", "Asset", "Non-current assets", 190, None,
     ["security deposit paid", "security deposit given", "capital advance"]),
    ("other_nc_assets", "Other non-current assets", "BS", "Asset", "Non-current assets", 200, None,
     []),
    ("current_investments", "Current investments", "BS", "Asset", "Current assets", 210, None,
     ["mutual fund", "current investment"]),
    ("inventories", "Inventories", "BS", "Asset", "Current assets", 220, None,
     ["closing stock", "stock", "inventory", "raw material", "finished goods", "stock-in-trade", "work-in-progress", "work in progress"]),
    ("trade_receivables", "Trade receivables", "BS", "Asset", "Current assets", 230, None,
     ["sundry debtor", "trade receivable", "debtors", "accounts receivable"]),
    ("cash_and_bank", "Cash and cash equivalents", "BS", "Asset", "Current assets", 240, None,
     ["cash in hand", "cash at bank", "bank account", "petty cash", "cash-in-hand", "fixed deposit", "fdr"]),
    ("st_loans_advances", "Short-term loans and advances", "BS", "Asset", "Current assets", 250, None,
     ["advance to supplier", "advance to staff", "prepaid expense", "loans and advances", "loans & advances", "tds receivable", "tcs", "advance tax", "gst input", "input tax credit", "itc"]),
    ("other_current_assets", "Other current assets", "BS", "Asset", "Current assets", 260, None,
     ["accrued income", "interest receivable"]),
    ("revenue_from_operations", "Revenue from operations", "PL", "Income", "Income", 300, None,
     ["sales", "revenue from operations", "service income", "gross receipts", "turnover", "gst sales"]),
    ("other_income", "Other income", "PL", "Income", "Income", 310, None,
     ["interest income", "interest received", "dividend income", "discount received", "rent received", "misc income", "miscellaneous income", "profit on sale"]),
    ("cost_of_materials", "Cost of materials consumed", "PL", "Expense", "Expenses", 320, None,
     ["material consumed", "cost of material", "raw material purchase"]),
    ("purchases_stock_in_trade", "Purchases of Stock-in-Trade", "PL", "Expense", "Expenses", 330, None,
     ["purchase", "gst purchase", "import purchase"]),
    ("changes_in_inventories", "Changes in inventories of finished goods, work-in-progress and stock-in-trade", "PL", "Expense", "Expenses", 340, None,
     ["increase decrease stock", "change in inventor", "stock adjustment", "opening stock"]),
    ("employee_benefits", "Employee benefits expense", "PL", "Expense", "Expenses", 350, None,
     ["salary", "wages", "staff welfare", "bonus", "gratuity expense", "provident fund", "esi", "employee benefit", "staff cost"]),
    ("finance_costs", "Finance costs", "PL", "Expense", "Expenses", 360, None,
     ["interest paid", "interest on loan", "interest expense", "bank charges", "loan processing fee", "finance cost", "interest on od", "interest on cc"]),
    ("depreciation_amortization", "Depreciation and amortization expense", "PL", "Expense", "Expenses", 370, None,
     ["depreciation", "amortisation", "amortization"]),
    ("other_expenses", "Other expenses", "PL", "Expense", "Expenses", 380, None,
     ["rent", "rates and taxes", "electricity", "power and fuel", "repairs", "printing", "stationery", "travelling", "conveyance", "telephone", "internet", "legal", "professional", "audit fee", "insurance", "advertisement", "commission", "freight", "postage", "general expense", "miscellaneous expense", "donation", "membership", "round off"]),
    ("partners_remuneration", "Remuneration and Interest to Partners", "PL", "Expense", "Profit Appropriation", 390, ["partnership"],
     ["partner remuneration", "partner salary", "interest on capital", "partner interest"]),
    ("current_tax", "Current tax", "PL", "Expense", "Tax Expense", 400, ["partnership", "llp"],
     ["provision for income tax", "income tax", "current tax"]),
    ("deferred_tax_pl", "Deferred tax", "PL", "Expense", "Tax Expense", 410, ["partnership", "llp"],
     ["deferred tax"]),
]

SECTION_ORDER_BS_EL = ["Owners' Fund", "Non-current liabilities", "Current liabilities"]
SECTION_ORDER_BS_ASSET = ["Non-current assets", "Current assets"]
